### ISSUE TITLE
Make YAFC show its version better

### ISSUE THREAD

**Issue by have-fun-was-taken** [have-fun-was-taken/yafc-ce#103]
When making releases, I want to set the exact version of the app. For instance, something like `0.6.2-RC1`. However, I have a suspicion that the current versioning accepts only the first three numbers from the Assembly/File version of the project, like `0.6.2`.

The to-do plan is as follows:
1. Check where exactly it takes the version from. The Assembly of the File version of the project.
2. Check if it can display more than just three numbers.
3. If it currently can't do so, make it that it can.

This is more of a note to self, but feel free to pick it up if you feel like.

**Comment by have-fun-was-taken** [comment]
On another hand, perhaps I should just use the first three numbers more. For instance, instead of Release Candidates, I can use the last digit.

**Comment by have-fun-was-taken** [comment]
I'm leaning towards the option of using the numbers more, but it's open to discussion.

**Comment by winex** [comment]
_hi guys! i'm glad you've trying to make YAFC better_

why ppl always try overcomplicating things?! last number was meant to be a patch as per `major.minor.patch` format

just do commits, commits, commits and then when you feel it's ready - increase the last number (or the second) and do release:
```
- 0.6.2
- 0.6.3
- 0.6.199
...
- 0.7.0 even if the change is only version number w/o any code, just to emphasize that all previous
work was tested and some bigger changes is happening or will be coming after this one
```
- ~~`*-rc1, *-rc2, pre-0.99, 0.9.1-pre1`~~... is just unintuitive and doesn't sort properly!
- which version comes after `1.1.9-rc1`?! -- most users will just say `1.2.0`!

if a specific version doesn't work / has bugs - one may return to previous one just by decreasing numbers. who wants the bleeding edge can use `master` branch and compile from source

for projects that have very busy release schedule - date-encoded version like `YY.MM(.DD)` is way better from user's point of view - it automatically tells you how old it is!
ex: `Mesa` project, `Ubuntu 22.04` distro release. _i'm using ~~`Debian 11`~~`Debian 12` not even knowing when it was released..._
