### ISSUE TITLE
Distribution Formats

### ISSUE THREAD

**Issue by Blu3wolf** [have-fun-was-taken/yafc-ce#11]
Another step could to to check if there is a pre-packaged format for your OS/distribution. For example there is one in AUR and there is a flatpak. I suppose there will be added more at some point?

_Originally posted by @veger in https://github.com/have-fun-was-taken/yafc-ce/issues/4#issuecomment-1923318806_
Discussing this here as this doesnt really relate to the PR.

The AUR PKGBUILD doesnt (currently) point to this repo (the community edition). Likewise, the flatpak points to a random fork (currently up-to-date with ShadowTheAge). 

Neither of those are distributions of this repo, although we could change that.

**Comment by have-fun-was-taken** [comment]
Hi! 
> we could change that

Can you please give more context regarding the situation?
Does the PR https://github.com/have-fun-was-taken/yafc-ce/pull/9 solve the issue with AUR?

**Comment by veger** [comment]
The 'Getting Started' section describes how to get YAFC-CE from a (zip) archive. There are at least 2 (that I know of) packaged versions of YAFC-CE available: AUR and ~Flatpak~ (it is only for YAFC ATM).

These pre-packaged solutions should have preference to the manual install using the archives IMO. So this ticket is about collecting those solutions and update the documentation to add them as a (preferred) way of installing to the 'Getting Started'.

**Comment by have-fun-was-taken** [comment]
> After https://github.com/have-fun-was-taken/yafc-ce/pull/9 is merged I guess we could update https://github.com/have-fun-was-taken/yafc-ce/pull/4 to address this?

Agreed.

> These pre-packaged solutions should have preference to the manual install using the archives

I agree with that.
So essentially, this issue is about setting up a proper way to install YAFC on non-Windows systems?
I'm all for it if you guys can pull it off.

**Comment by Blu3wolf** [comment]
Its a start on that. There's a lot of non-windows system variation out there, with different packaging requirements. The point of this issue specifically (for me) was to discuss the reference to the Flathub package, which is currently highlighted as being a way to install this - but in fact it installs the original yafc, not the community edition. 

I don't really use flathub, but perhaps someone is interested in making a flatpak and putting it on flathub?

**Comment by Blu3wolf** [comment]
So now that #9 is merged, is there anything else to cover in this issue? This was mostly to highlight the flathub being pointed to, which is the old version rather than this community version. 

Now that that is spelled out in the text, this could be closed?

**Comment by have-fun-was-taken** [comment]
Yes. Thank you for your contribution!
