### ISSUE TITLE
[Discussion] Change CostPerPollution to zero

### ISSUE THREAD

**Issue by have-fun-was-taken** [have-fun-was-taken/yafc-ce#111]
YAFC [considers](https://github.com/have-fun-was-taken/yafc-ce/blob/master/Yafc.Model/Analysis/CostAnalysis.cs#L22) a recipe more costly if it pollutes more, when I suspect that most of the Pyanodon users play without pollution. 

Therefore, I consider changing the pollution cost to zero. It's not worth it to make it configurable because I think the target audience of YAFC either plays without pollution or doesn't care about it.

What do you guys think?

**Comment by veger** [comment]
I didn't even know pollution was (part of) the price calculation :rofl: 

Yes, I play without pollution (basically always, also for non py games), as I am more interested in the logistics for the game
