### ISSUE TITLE
Request For Comments: Contributor's Guide

### ISSUE THREAD

**Issue by have-fun-was-taken** [have-fun-was-taken/yafc-ce#12]
@veger @Blu3wolf @SWeini @klaborda and everyone else,

I made a [Contributor's Guide](https://github.com/have-fun-was-taken/yafc-ce/blob/master/Docs/ContributorsGuide.md) to improve the quality of the future PRs.  
I aimed to relay the key points that we would like to see in the PRs.
Please let me know if there's anything that you would like to change in it.

**Comment by veger** [comment]
Looks reasonable to me!

**Comment by have-fun-was-taken** [comment]
Thank you guys for the feedback!
