### ISSUE TITLE
(Investigation) Why do recipes sometimes show up for disabled recipes and sometimes do not?

### ISSUE THREAD

**Issue by Dorus** [have-fun-was-taken/yafc-ce#122]
From https://github.com/have-fun-was-taken/yafc-ce/pull/121#issuecomment-2104416614

> One thing i noticed while investigating this:
> 
> Before when you disable a recipe, the item row is emptied. Old projects still have this state stored:
> 
> ![afbeelding](https://private-user-images.githubusercontent.com/4461459/329558154-235d1cff-3f03-4248-b58b-bee6a0311ce7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzk1MzUsIm5iZiI6MTcxNTMzOTIzNSwicGF0aCI6Ii80NDYxNDU5LzMyOTU1ODE1NC0yMzVkMWNmZi0zZjAzLTQyNDgtYjU4Yi1iZWU2YTAzMTFjZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTBUMTEwNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzIyMzY2MmM3ZDMyYjYyZThkMGNlNThlZmQwZWFiNmEwNzRhMDRmNWU4NjIxYmI4YTM3ZjIxNjNkYzNhODk0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jcB2raT04lUhuIJNXdT09N_JqxInTrJH01XovbS0TMI)
> 
> If i enable them now and disable again, i get the recipes visible: ![afbeelding](https://private-user-images.githubusercontent.com/4461459/329558259-e71dede0-5b5c-461c-8962-8f8f446304dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzk1MzUsIm5iZiI6MTcxNTMzOTIzNSwicGF0aCI6Ii80NDYxNDU5LzMyOTU1ODI1OS1lNzFkZWRlMC01YjVjLTQ2MWMtODk2Mi04ZjhmNDQ2MzA0ZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTBUMTEwNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzNiMGRlYzFmMjIxZWFhMGZjZjU5ZTkyOWJlNDk5YTI5ZGQwZTdlNWY0MTBlYWNlYmFiMzE4NjhkMmU3ZGFhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HHGo8j851jMUPUdlUgnoXTQT_2-Ej1KVWpDR1Ojj9No)
> 
> I'm not sure if this was intended, i tried to go to older versions along the master branch, but couldn't find any yet without this problem until i ran into the ones with the libf problem.

**Comment by DaleStan** [comment]
For what it's worth, this behavior has been around in every version I tested back to v0.5.5.

**Comment by DaleStan** [comment]
I've figured out what's going on here. My inclination is *almost* to make disabled recipes look like this
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/21223975/7f7c57b7-ca66-4428-9051-068210263abd)
but it’s not obvious how to make that module/beacon display work on a freshly-loaded file.

Either of these are easy. I can also display boxes for the building and fuel, or I could limit the display to just a single box even if there are multiple inputs or products, like the module display.
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/21223975/8954c4da-4bc3-4951-9ca5-cd2bf9c839a6)

In all three cases, the link information is not displayed. For one, I figure that if you cared about whether you had production for small parts, you shouldn't have disabled that recipe, and for another, that information doesn't get updated for disabled recipes.

What thoughts do you have?

**Comment by Dorus** [comment]
I would keep buildings and fuel since that's an important decision of what the recipe actually is. As long as it's clear these are not enabled. Hiding the ingredients takes away a lot of visual clutter so that's preferable i think (?)

**Comment by Dorus** [comment]
> In all three cases, the link information is not displayed.

It's still displayed on the other half of the link (if any). So that's fine i think.
