### ISSUE TITLE
Electric Boiling marked as inaccessible

### ISSUE THREAD

**Issue by RandBlade** [have-fun-was-taken/yafc-ce#139]
YAFC v0.6.4.0

For some reason electric boiling is suddenly inaccessible, because it seems to think the electric boiler can not be placed. Creating a new, blank project duplicated the problem.

PyAE with QoL mods, no mods changed recently so I don't know what caused the issue. 

Discussed on Py YAFC channel with have fun.

Blank new save attached.
[Blank New Save.zip](https://github.com/have-fun-was-taken/yafc-ce/files/15475112/Blank.New.Save.zip)

**Comment by RandBlade** [comment]
Updating to YAFC 0.7.0 fixed it.

Weird.

**Comment by have-fun-was-taken** [comment]
Closing as resolved. Please reopen it if you encounter the bug in newer versions.
