### ISSUE TITLE
Make it possible to scroll past the bottom recipe

### ISSUE THREAD

**Issue by have-fun-was-taken** [have-fun-was-taken/yafc-ce#14]
In long chains of recipes, the bottom recipe is near the bottom edge of the app, which is uncomfortable.  
It would be good to scroll past the bottom recipe, so the lowest chosen recipe is in the middle of the app instead of its bottom edge

**Comment by have-fun-was-taken** [comment]
This becomes a hurdle instead of an inconvenience when the horizontal bar appears and hides the numbers of the bottom row.
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/73699379/317994cc-6782-472e-95df-24f06389ac6d)

**Comment by have-fun-was-taken** [comment]
After the [counterexample](https://github.com/have-fun-was-taken/yafc-ce/pull/50#issuecomment-1957317200) of half an empty screen, I think that a couple rows of the empty space is sufficient.

**Comment by veger** [comment]
> This becomes a hurdle instead of an inconvenience when the horizontal bar appears and hides the numbers of the bottom row.

Proper fix for this is to add a bit of padding when the horizontal scrollbar is activated.
