### ISSUE TITLE
[Discussion] Drop the changelog in favor of release notes?

### ISSUE THREAD

**Issue by have-fun-was-taken** [have-fun-was-taken/yafc-ce#153]
The changelog is essentially duplicated. Once in [changelog.txt](https://github.com/have-fun-was-taken/yafc-ce/blob/master/changelog.txt), once in [release notes](https://github.com/have-fun-was-taken/yafc-ce/releases). 
The duplication adds overhead to keeping the txt version up-to-date because not all PRs remember to add to the changelog file.

The only advantage that I see to the `changelog.txt` is that it would help to save the summary of updates if we would need to host the repo elsewhere. However, I think that the current upkeep costs outweigh the gains if we would need to rehost.

I introduced the changelog file in analogy to the pyanodons changelogs. However, now I understand that the situation is different for YAFC because its changelog is not broadcasted on the Factorio mod page.

Therefore, I think about leaving only release notes and abandoning `changelog.txt`.

What do you guys think? Is there anything else to consider? Please share your opinions.

**Comment by Dorus** [comment]
I always thought you had changelog.txt to make it easy to fill release notes, and also to keep a historical log. With release notes, how will PR's describe changes?

**Comment by alexbarrett** [comment]
Other than the effort of duplication, I don't see any advantages to removing `changelog.txt`.

 A plain text file under version control is:

1. Guaranteed to be distributed with the source code, even when cloned from a source other than GitHub.
2. Discoverable without having to navigate to the GitHub release pages.
3. Associated line-by-line with an associated commit, potentially serving as a form of link to associated commits.
4. Available for read and write when working offline.
5. Independent of the SCM platform.

Perhaps the release notes could be automatically populated from `changelog.txt` in a release script?

**Comment by have-fun-was-taken** [comment]
There is an option on github to make release notes automatically. It writes down all PRs since the last release, so I just have to trim and summarize instead of re-checking if everything is there on top of that.

> I always thought you had changelog.txt [...] to keep a historical log

I think that the Release Notes will serve that purpose. If someone wants the details, they can refer to the linked PRs or the commits.

> With release notes, how will PR's describe changes?

The [0.7.0](https://github.com/have-fun-was-taken/yafc-ce/releases/tag/0.7.0) was done this way, so you can expect things similar to that onward.

> Guaranteed to be distributed with the source code, even when cloned from a source other than GitHub.

That's a solid point. If someone wants to fork the repo, the releases don't get forked, so the release-based changelog is lost to the fork.

> Discoverable without having to navigate to the GitHub release pages.

A valid point for a developer.

> Associated line-by-line with an associated commit, potentially serving as a form of link to associated commits.

Agreed.

> Available for read and write when working offline.

_Theoretically_ sure, such a case can happen.

> Independent of the SCM platform.

The chances that we need to rehost elsewhere are minuscule, but yes.

Overall, yes, good points! With that many points to keep the changelog, I think the issue is resolved in favor of keeping it.

**Comment by veger** [comment]
> > Associated line-by-line with an associated commit, potentially serving as a form of link to associated commits.
>
> Agreed.

For me this is a strong point as well
