### ISSUE TITLE
Remove local paths for releases

### ISSUE THREAD

**Issue by veger** [have-fun-was-taken/yafc-ce#164]
As mentioned in https://github.com/have-fun-was-taken/yafc-ce/issues/159#issuecomment-2175830992 the releases contain the paths of the local machine that was used to build the release.

I assume there is a way with C# / .net to make releases without this (private) information, but only show the paths from the root of the project/repo.

I think we should improve our release script, so fix this.

**Comment by Dorus** [comment]
https://softwareengineering.stackexchange.com/a/421590
