### ISSUE TITLE
Cannot drag scroll tab search scrollbar

### ISSUE THREAD

**Issue by Dorus** [have-fun-was-taken/yafc-ce#168]
![afbeelding](https://github.com/have-fun-was-taken/yafc-ce/assets/4461459/5427fc20-04a4-4552-ae8d-946c02fef094)

Cannot drag scroll tab search scrollbar.

**Comment by veger** [comment]
Hm... I thought I fixed all scrollbars in #161...

Scrollbars are (somehow) horrible in YAFC, they keep on breaking. Maybe it would be better to have a good thought and complete redesign their implementation? :thinking: 

Currently having them stick at the correct position is hard, especially at the bottom, as the (ImGui) context is partial (often the Height is not filled in) and it is unclear which of the contexts is the correct one to use. Also the scrollbars draw to the current context/state, making it very hard to draw them at the edges of the screen/another context...

Unfortunately none of us are (real) SDL UI experts... So rewriting this part might be too much (#161 took me a _lot_ of effort and is still not perfect)

**Comment by Dorus** [comment]
Well at least, this was broken before and after 161 ;)

**Comment by veger** [comment]
BTW I just tried, scroll wheel does work (as a work-around)
