### ISSUE TITLE
Incorrect version in window title

### ISSUE THREAD

**Issue by sunrosa** [have-fun-was-taken/yafc-ce#172]
On a freshly downloaded YAFC-CE version 0.7.2, the program calls itself 0.7.1 in the window title.

**Comment by veger** [comment]
@have-fun-was-taken most likely forgot to update the/this version number. It is only visual, so your download is the newest version. (I just double checked the download)

**Comment by have-fun-was-taken** [comment]
True, I forgot to update the version. I'll make a document with the steps for the release to not forget again.

**Comment by have-fun-was-taken** [comment]
@sunrosa I've fixed the [release](https://github.com/have-fun-was-taken/yafc-ce/releases/tag/0.7.2), made the [release algorithm](https://github.com/have-fun-was-taken/yafc-ce/blob/master/Docs/ReleaseAlgorithm.md) to not forget about it in the future, and updated the version preemtively to not bother about it with the next release. 
Please verify.

**Comment by sunrosa** [comment]
Latest is fixed.
