### ISSUE TITLE
[Maintenance] Upgrade to .Net 8

### ISSUE THREAD

**Issue by shihan42** [have-fun-was-taken/yafc-ce#25]
Reasons to upgrade:
- .Net 8 brought some improvements for AOT and JIT
- It is the next LTS version after .Net 6
- Staying at the front prevents accumulating technical debt ;-)

**Comment by veger** [comment]
In the 8.0 RC1 release notes it is mentioned that icons, manifests, etc. are properly embedded in the binaries now. So it might fix #36. So when this is implemented, we should check if #36 (and/or its fix is obsolete).

**Comment by Dorus** [comment]
This is done.
