### ISSUE TITLE
[Bug] Popup "Target technology for cost analysis" in Preferences isn't wide enough

### ISSUE THREAD

**Issue by shihan42** [have-fun-was-taken/yafc-ce#27]
**OS**: Win11
**YAFC version:** https://github.com/have-fun-was-taken/yafc-ce/commit/b0fa78f6b4e91e6b572ec8eec00c5c9ae950bed1

The popup is not wide enough. Increasing width or implementing word wrapping should solve the problem.

![grafik](https://github.com/have-fun-was-taken/yafc-ce/assets/12949966/822efa0d-113b-4978-90bd-092fb8ab75a5)

**Comment by shihan42** [comment]
Ok, this one is harder than expected. Somehow the bounding rectangle ignores the header text. I'm digging through it, but since immediate mode guis are a pita to debug, this will take some time.

**Comment by veger** [comment]
It is already broken in the upstream project, in the commit where YAFC CE is forked from: https://github.com/ShadowTheAge/yafc/commit/fd80865b3429e99d592426f2107a2dbe9a0eb553

And so it has nothing to do with #31 or #34 (saves some work of backtracking the issue)
