### ISSUE TITLE
Add Spotless

### ISSUE THREAD

**Issue by have-fun-was-taken** [have-fun-was-taken/yafc-ce#3]
[Spotless](https://github.com/diffplug/spotless) can prevent getting bogged down with code-style nitpicks in the review phase.

**Comment by have-fun-was-taken** [comment]
I agree. If I remember correctly, it shoud be possible to apply Spotless only to the files affected by the PR.

**Comment by veger** [comment]
FYI A while back, I added an [.editorconfig](https://gist.github.com/veger/75d8d55bf3650835e7d5e82dc57d0715) to the root of my (local) repo, which includes some basic formatting according to the coding style of YAFC.

It configures
* indentation styles (spaces no tabs)
* (one) disabled diagnostics (which makes sense for C# 9.0 not for ours)
* dotnet coding styles
* C# coding styles

My IDE (vs code) pick this up (I guess the C# extension) and applies this when formatting the file. Before the IDE messed up the formatting when saving YAFC files, and now it seems to be the same after formatting. Making my coding life easier.

**Comment by have-fun-was-taken** [comment]
In general, a config is a good addition. Please let us know if the config you [linked](https://gist.github.com/veger/75d8d55bf3650835e7d5e82dc57d0715) is the one you suggest to add to this project.

**Comment by veger** [comment]
I can be a starting point? From there we could always tweak it to make it better for the project.

Also, I don't know which IDEs pick up the `.editorconfig` files, but it is some standard format. So hopefully all major ones use it... :smile: 

I'll make a PR to add it

**Comment by have-fun-was-taken** [comment]
From my intial search, it seems like there's no widely known way to add Spotless into C#. 
C# has [Code Cleanup](https://learn.microsoft.com/en-us/visualstudio/ide/whats-new-visual-studio-2019?view=vs-2019#code-cleanup), and we can update warnings into errors if necessary.  
I'll see what can be done with it.

**Comment by have-fun-was-taken** [comment]
ReSharper can be an option if we get their free OSS license. I've sent a request.

**Comment by have-fun-was-taken** [comment]
Essentially, Visual Studio has its own Spotless with `.editorconfig`. We just need to set the violations to the `error` level of severity if we want these rules to be followed.
