### ISSUE TITLE
Add icon to window titlebar

### ISSUE THREAD

**Issue by veger** [have-fun-was-taken/yafc-ce#36]
Since #32 we have an icon, so it makes sense to add it to the window title bar as well:

![image](https://github.com/have-fun-was-taken/yafc-ce/assets/171827/19a1443a-0ba8-4f76-92c4-c6cfa3646d16)

I did a quick search and found [SDL_SetWindowIcon()](https://wiki.libsdl.org/SDL2/SDL_SetWindowIcon), so we could load the icon into a `SDL_Surface` and set it as the window icon.

`YAFCui/Core/WindowMain.cs` would be the place to start to imeplement this enhancement

**Comment by have-fun-was-taken** [comment]
If I see it correctly, the icon is now in the titlebar. Is this issue completed then? 
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/73699379/34e16769-a735-4eb1-9f71-17cc64a954cf)

**Comment by veger** [comment]
Maybe automatically in Windows? For Linux it is as shown in the screenshot. No idea for MacOS.

**Comment by veger** [comment]
I implemented it, and even figured that the new icon should be part of the release.
Waiting for #64 to be merged in order to make a PR.
