### ISSUE TITLE
Add a recipe for research consumption

### ISSUE THREAD

**Issue by have-fun-was-taken** [have-fun-was-taken/yafc-ce#53]
A developer of Pyanodons, Kingarthur1991, would like to have a pseudo-recipe to calculate the research pack consumption in a lab. The recipe is expected to account for the research speed and the productivity buffs.

Original quote:
> Off the top of my head a nice feature would be able to have a fake recipe for calculating science pack consumption in the labs. 
With the milestones and things it should be possible to have it at least show what aware of lab speed and allow for module effects

**Comment by veger** [comment]
So for example you say: "I want to do 10 SPM" and the recipe will require the needed ingredients? So you can design the rest of the faction depending on this?

**Comment by have-fun-was-taken** [comment]
Yes. I think it is analogous to the Electricity generation. 

One of the ways to implement it would be:
A user chooses Science from the products, selects the only science-production recipe that is the lab, chooses the target technology for that recipe, and configures the speed and productivity through modules.

**Comment by veger** [comment]
Why not just having something like this?

![image](https://github.com/have-fun-was-taken/yafc-ce/assets/171827/c65d0293-ddcb-4631-a663-8faaf6a9b540)

I currently have setup some void recipes (in a separate production sheet) that request "items per second", both science packs as regular items.

So the the feature would become "be able to request items per second". Which could work for both science and the other items. And does not depend on technology goals, productivity, etc. Making the whole feature more simple to use and implement?

**Comment by have-fun-was-taken** [comment]
> I currently have setup some void recipes

In my understanding of the Science recipe, the problem it solves is showing how many labs and with what upgrades and vatbrains it takes to produce that much Science per second / minute / hour. If your solution does that, then please let us know how.

**Comment by veger** [comment]
No, in only calculates the amount of ingredients required for a certain amount of "items per minute".

This issue is more about calculating the amount of required labs to _consume_ a certain amount of science per minute?
