### ISSUE TITLE
A way to hide nests or lines on the production sheet

### ISSUE THREAD

**Issue by RandBlade** [have-fun-was-taken/yafc-ce#59]
It is already possible to mark lines with ticks or similar symbols but that doesn't materially change the way the sheet appears, other than that small check mark being there.

It would be nice to be able to mark a line or nest as completed for when we have built out that line/nest so that it then disappears, or alternatively is perhaps greyed out.

That way incomplete lines/nests that we need to develop would be visibly different to completed lines/nests.

The simplest way to change this might be to simply get the checkmark if implemented to grey out the line/nest that checkmark is next to then, if that's possible.

A more complex but possibly more useful way to do it would be to have a hidden/unhidden toggle and then able to mark lines/nests as hidden, so they don't even appear on the sheet (but are still there in the background, unless you've toggled to unhide mode.

I hope either way or something similar can be implemented. Thank you for considering it.

**Comment by shihan42** [comment]
Something like this:
![checkmarked_row](https://github.com/have-fun-was-taken/yafc-ce/assets/12949966/fbcef8ea-7242-480a-9772-dfcba1ccaae2)

**Comment by RandBlade** [comment]
That looks a million times better if it can be done, thank you.

**Comment by shihan42** [comment]
First draft (working program, no Photoshop shenanigans):
![graphic](https://github.com/have-fun-was-taken/yafc-ce/assets/12949966/18efb3b4-995d-4c66-9555-bd63c6c83d9d)

**Comment by SWeini** [comment]
the gray text makes me instantly think these recipes are disabled. probably the green background is enough of visual distinction, no need for gray text.

**Comment by RandBlade** [comment]
Personally I really like the grey text with the green background, it fades it out nicely and distinctly.

**Comment by shihan42** [comment]
Ok, the coloring is a thing. Perhaps the text is not light grey but light green?

And I think about adding yellow and red for the marks next to the checkmark. What do you think?

**Comment by RandBlade** [comment]
Light green would work, so long as the text were still visible against a green background. 

And amber and red could be quite useful too I suppose. 

Thanks for working on this.

**Comment by shihan42** [comment]
Ok, this is the current state:
![pic](https://github.com/have-fun-was-taken/yafc-ce/assets/12949966/e1bd2343-bf56-4fe5-93ec-97d93fbb1d5e)

The text color is a darker variant with suitable contrast.
Tagging a nested recipe also highlights every child, but only if these childs don't have tags themselves.
What do you think?

(No dark theme yet, but that is trivial to solve)

**Comment by veger** [comment]
Looks nice to me.

The yellow (amber?) text could use a little more contrast maybe, but  the rest is readable enough (for me).

One question though: Does it also work with solver errors (e.g. solver puts a exclamation mark to indicate errors on the recipes)? No idea if we want this or not, just curious.

**Comment by RandBlade** [comment]
I love it, thank you. The yellow and red is a good idea, could imagine using that with green for done, yellow for what I'll work on next and red for those I'm postponing for later. 

Look forward to being able to download a version of this, you've done a really good job, thank you. Agree with the logic you've done for nest children too.

**Comment by shihan42** [comment]
So, long time no see, I had some busy days...

I more or less prepared the PR, but @veger opened #70 and that clashes with the changes here.
So I'll wait for the other PR to be merged and then sort out the conflicts that will arise (since I changed the coloring code, too).

But it's not forgotten. It's just that some RL appeared ;)

**Comment by RandBlade** [comment]
What does it mean about being merged? Is there a version now with this working, or not yet?

**Comment by veger** [comment]
The merged feature is about showing a different color for overproduction (PR #70).
@shihan42 was waiting for the PR to be merges, as their changes are dependent on/influenced by that particular PR.

With this out of the way the path is available to finish up the code for this issue. But keep in mind that we all have a life next all of this. So please be patient until there is an opportunity for @shihan42 to finish it.

**Comment by RandBlade** [comment]
Thanks, absolutely being patient, just wasn't sure what it meant about being merged. Thanks for the explanation.

**Comment by shihan42** [comment]
At last, I found the time to submit the PR. Sorry for the lengthy delay :-/

**Comment by RandBlade** [comment]
Thanks so much for doing this!
