### ISSUE TITLE
Py science milestones are not loaded on PyHM

### ISSUE THREAD

**Issue by Sriki13** [have-fun-was-taken/yafc-ce#69]
YAFC-CE v0.6.1 on WIndows 11

On project load, YAFC will only load the non py science packs with incorrect icons. Trying to add the missing science packs does not do anything.

![image](https://github.com/have-fun-was-taken/yafc-ce/assets/25670169/d97bf7af-4507-4be1-be48-77371798f386)

Note that the milestones and icons are still correct in the milestone editor.

![image](https://github.com/have-fun-was-taken/yafc-ce/assets/25670169/a87b8642-98cb-4aa8-9e33-68264d120318)

Reproduced on a fresh save with only PyHM loaded. Here is the save.

[PYHM-YAFC-CE-Test.zip](https://github.com/have-fun-was-taken/yafc-ce/files/14500547/PYHM-YAFC-CE-Test.zip)

**Comment by Sriki13** [comment]
Well, I reloaded the same save this morning, did the exact same thing with some more mods, and the issue's gone. Mind you, I did try multiple times yesterday too.
 Seems like whatever happened there may not be easily reproductible. Feel free to close this if you can't.

**Comment by shihan42** [comment]
That is something I also encountered, although I used other mods. Perhaps somethings wrong with the internal icon cache.

I suppose we keep this open, but rename it since the problem seems to occur with and without PyHM.

**Comment by veger** [comment]
AFAIK icons are not cached but loaded directly from the mods?

But it would be good to keep the issue open as multiple people encountered this problem. (I never encountered this myself, I play with full 'pure' py mod-suite on Linux)

**Comment by shihan42** [comment]
Sorry, not icon cache. I meant icon collection.
It has something to do with this line, I believe:
https://github.com/have-fun-was-taken/yafc-ce/blob/f416db9c101e5382190f741c10eb2efc6d94aaa7/YAFC/Windows/WelcomeScreen.cs#L67

I'm not sure yet how that comes together, but there is something sketchy in the handling of these icons.

#54 yeah, I'll look into it.

**Comment by DaleStan** [comment]
I'm guessing I fixed this in e39248e0 and #127.

**Comment by DaleStan** [comment]
This looks like it's fixed to me; I synced mods with the save and got this milestone display when I created a new project, both with a freshly-started Yafc and having previously loaded a different modpack.
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/21223975/4b8a230a-25dc-40ea-819c-4c1900f7dc0d)
