### ISSUE TITLE
YAFC fails to launch from a command line without an existing project

### ISSUE THREAD

**Issue by have-fun-was-taken** [have-fun-was-taken/yafc-ce#78]
Use case:
You're a new user and you want to launch YAFC from the command line. You can't do that because without the `project` argument, `args.Length < 3` becomes `true`, which leads to YAFC not loading.

I didn't reproduce this case myself, and it's low priority due to the low number of console users.  
I'm creating this issue to not forget that this bug exists.

**Comment by ashprice** [comment]
Figured I'd write a comment and point out that console is likely the default mode of interaction for linux users. 

A temporary work around is simple: create a dummy file named foo.yafc, pass the directories to yafc (eg. `./YAFC foo.yafc ~/.local/share/Steam/steamapps/common/Factorio/data ~/.factorio/mods`), and then after being prompted with an error, you'll be given the project selection screen. Delete the project selection line to create a new project, and then after creation, save it to a different name or overwrite the previous dummy file.

**Comment by have-fun-was-taken** [comment]
The test cases that the issue is expected to pass:
1. Start YAFC from CLI with the project name that doesn't exist. YAFC notifies that it haven't found that project-file and will create it. YAFC starts successfully and saves the changes into that new project.
2. Start YAFC from CLI with the already existing project. YAFC starts successfully and saves the changes into that project.

**Comment by have-fun-was-taken** [comment]
Additional clarification on use cases from the discussion in Discord:
Starting ./YAFC without any arguments => YAFC starts with an empty project definition on the welcome screen
Starting ./YAFC path/to/data/directory => YAFC starts with a fresh project, using the supplied data
Starting ./YAFC path/to/data/directory <optional arguments> => YAFC starts and tries to load the project and mods folder, if supplied
