### ISSUE TITLE
Indicate overproduction better

### ISSUE THREAD

**Issue by LoneWolfProductions** [have-fun-was-taken/yafc-ce#8]
Could it be possible to give an item that has the "over production allowed" get a different background color or visual mark?
This would make it easier to look back and instantly know what is over producing at a later time

For example in the picture below I am allowing coal to be overproduced. 
However I need to deal with the over production in such a way it's not causing deadlocks.

When I build this production line I missed that I needed to pay attention to this giving me a deadlock in game and a lot of searching out why it was happening until I realized I missed the over production I allowed..

I believe if I had the visual indicator I would not have had this problem.
That is why I'm Requesting to visualy change the background color or something alike of items that are allowed to be overproduced.

![image](https://user-images.githubusercontent.com/30441722/229454098-8902f487-1738-4325-b713-0f3999880e40.png)

**Comment by have-fun-was-taken** [comment]
Although in my case, it was also possible to just unlink the resource, so I'm not sure if this use case is widespread.

**Comment by veger** [comment]
When you link the overproduction you still have the guarantee that there is at least sufficient production of the item. So there is a (niche) use-case. Usually unlinking the resource works yes.

I am (coincidentally) taking a look what info can be used to render this differently, but it is very deeply hidden in the data structures... So I might just give up and make a PR of the refactored coloring code that I already did.

**Comment by have-fun-was-taken** [comment]
If anyone has time for it, a short decription of the minimal example would be appreciated. Just to switch from hypothethicals into the actual use case.

**Comment by veger** [comment]
I was able to throw something together, the green (color was available, we could use another/new color) backgrounds show the overproduction for produced items:
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/171827/0e8df660-9599-4064-a18c-40abc3bd2ecc)

It works for direct (blue, microfiber) and indirect (brown-ish, activated carbon) links. Note that the consuming side (ingredients) is not green.

But this also (besides the use-case) adds another problem: We have already quite a bunch of color codings (errors, links, indirect links). Adding yet another (or two if we want to show actual overproduction next to allowed over production) color to the mix begs the question about priorities as we can only pick on color... So errors obviously have highest priority, but what about links and indirect links?

This is besides the minimal example that @have-fun-was-taken is asking for.

**Comment by veger** [comment]
I picked magenta as a new color, see PR for some screenshots. It is a color that does not look like any of the other colors YAFC is using. But I am not an expert on coloring, so feel free to do suggestions for other colors :smile:

**Comment by veger** [comment]
In the end we decided to use magenta to indicate _actual_ overproduction. Allowed overproduction is not shown to reduce the visual clutter with (even) more colors.
