### ISSUE TITLE
Crash off of first install on 0.6.2

### ISSUE THREAD

**Issue by Braxbro** [have-fun-was-taken/yafc-ce#82]
When installing YAFC-CE from scratch (ver. 0.6.2) on a separate disk from my Factorio install (same PC) YAFC launches to a blank white screen then closes immediately.

I'm running on Windows 10 Pro.

Steps to reproduce:
- Don't have YAFC-CE at all
- Install YAFC-CE by downloading 0.6.2 & extracting it to a separate disk (with symlinks to the main disk, if that matters?)
- Attempt to launch YAFC-CE

**Comment by nnguyen259** [comment]
I also get the crash from a fresh install with no symlink involved

**Comment by have-fun-was-taken** [comment]
Removing the tag `help wanted` from this ticket since we have a bigger [fire](https://github.com/have-fun-was-taken/yafc-ce/issues/83) to put out.

**Comment by AnakinShieh** [comment]
failed to start on both windows and mac(apple silicon)

**Comment by shihan42** [comment]
How does this fail? Can you describe what happens?

And @nnguyen259: Which OS? Are Factorio and YAFC also on different drives?

The more information we have, the easier a fix would be.

**Comment by have-fun-was-taken** [comment]
On a side note, I suggest to try the recent [pre-release](https://github.com/have-fun-was-taken/yafc-ce/releases/tag/0.6.3-RC1) to see if anything changes.

**Comment by shihan42** [comment]
I'm reopening this since I'd like to have some validation if it really fixed the crash.

**Comment by shadghost** [comment]
I tried both the RC and the 0.6.2 and it just starts a white window and then crashes in Windows. Are there logs anywhere that I can post here?

**Comment by have-fun-was-taken** [comment]
@shadghost please try versions prevoius to 0.6.2 and let us know the results. That will help to understand the issue better.

**Comment by shadghost** [comment]
Workaround: Download / start 0.6.1, it will error out on flib, after you get to the flib error download and start 0.6.3-RC1 and it will start and everything works.

**Comment by have-fun-was-taken** [comment]
I've made a [release](https://github.com/have-fun-was-taken/yafc-ce/releases/tag/0.6.3-RC2) yesterday that should include the fix to that problem. Feel free to try it out.

**Comment by shihan42** [comment]
Any news on this?

**Comment by have-fun-was-taken** [comment]
I think we close this one and make a new issue if more crashes get reported.
